---
language: node_js
node_js:
  - 8
  - 10
  - 12
env:
  global:
    secure: yzmDF+URsCv5t7P3z0jEceD8bD1cKbXLkdx7fur7zqSQCUNKYHNeBi2ga63tIGm0Mkq1XaJHY4WA3x/50UEf3/sgs/sm9U6OepGg74XMEWFOrF1sQN3bB+d53pChAQHDT8eMfeuy+VS/zyWcgotuw5NQtbQ+8ioT2mG80wgdenBIwWR8OXtOmDKUIaG6d/AaP6XY4zgPmynzK1lZQFGpsVYRRY7xUTbOnKBHFuAxbVKWioIh1PDmq77YeznmP2rH71Br6wZQQ05/SrPkAPu5PEQ/vAZw8bX7IS1WPVlnwIEall1jEkAMgg/7kdkqp56rr5yKtNGC113mzhHt5m1xcxpwSEhrfVlPqBH/adb46Alzwis6787ERNY9xY4S/U7hE2sQYngLWk6I4ye5abeFM/PnIcs06hnLUc6WStUMm9VFuq/T+YcUA3ndDfWMU/tLvsApvs0joj0nOD+uqQjXEtTfRZD7YPYVO7q/+kj6FD7L6gbXuX+jOVjGXf26p+/YYiY7B8I9CA9UOKnWhYCGOyDfjdbtAxNDacxjDbiLdRgJ1FBafDpKakdDWTJip8Jn+IYsoOLmRSNhRcoPMRouhdG1NHKeRBDc44vtkC91j6UkiZSvIwx46yE/BZAJXNvBYg29niT7fGykftTThUq28/jGwYSKzsx6/1K+WPDDU54=
script:
  npm run test:ci
